'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { createContext, useState } from 'react'
import LanguageContextProvider from '@/contexts/LanguageContext'
//import LanguageContextProvider from '@/contexts/LanguageContext'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const LanguageContext = createContext('fr')


export default function RootLayout({ children }: { children: React.ReactNode }) {
 

  const [lang, setLang] = useState('fr')

  return (
    <html lang={lang}>
      <body className={inter.className}>
      <LanguageContextProvider value={lang}>
          <Navbar></Navbar>
          {children}
      </LanguageContextProvider>

      </body>
    </html>
  )
}
